function hfigs = plotMonteCarlo_gpsins(errors, traj)
%PLOTMONTECARLO_GPSINS creates hair plots of the estimation error for each
%state
[n, ~, ~] = size(errors);
hfigs = zeros(n,1);
ylabels = {'X Satellite Position Estimate Error (m)',...
    'Y Satellite Position Estimate Error (m)',...
    'Z Satellite Position Estimate Error (m)',...
    'X Satellite Velocity Estimate Error (m/s)',...
    'Y Satellite Velocity Estimate Error (m/s)',...
    'Z Satellite Velocity Estimate Error (m/s)',...
    'X Satellite Attitude Estimate Error (rad)',...
    'Y Satellite Attitude Estimate Error (rad)',...
    'Z Satellite Attitude Estimate Error (rad)',...
    'X Beacon Position Estimate Error (m)',...
    'Y Beacon Position Estimate Error (m)',...
    'Z Beacon Position Estimate Error (m)',...
    'X Gyro Bias Estimate Error (rad/s)',...
    'Y Gyro Bias Estimate Error (rad/s)',...
    'Z Gyro Bias Estimate Error (rad/s)',...
    'Range Bias Estimate Error (m)',...
    'Doppler Bias Estimate Error (m/s)',...
    'X Grav Bias Estimate Error (m/s^2)',...
    'Y Grav Bias Estimate Error (m/s^2)',...
    'Z Grav Bias Estimate Error (m/s^2)',...
    'X SC Misalignment Estimate Error (rad)',...
    'Y SC Misalignment Estimate Error (rad)',...
    'Z SC Misalignment Estimate Error (rad)',...
    'X TC Misalignment Estimate Error (rad)',...
    'Y TC Misalignment Estimate Error (rad)',...
    'Z TC Misalignment Estimate Error (rad)',...
    'X Feature Position Estimate Error (m)',...
    'Y Feature Position Estimate Error (m)',...
    'Z Feature Position Estimate Error (m)'};
for i=1:n
    hfigs(i) = figure;
    hold on;
    grid on;
    ensemble = squeeze(errors(i,:,:));
    filter_cov = squeeze(traj.navCov(i,i,:));
    h_hair = stairs(traj.time_nav/3600, ensemble,'Color',[0.8 0.8 0.8]);
    h_filter_cov = stairs(traj.time_nav/3600, ...
        [3*sqrt(filter_cov) -3*sqrt(filter_cov)],'--r');
    legend([h_hair(1), h_filter_cov(1)],'MC Runs','EKF 3\sigma Cov')
    xlabel('Time (hours)')
    ylabel(ylabels{i})
    set(gca, 'FontSize', 12)
end

% 
% hfigs(end+1) = figure;
% hold on
% h_true = plot3(traj.truthState(1,:)',...
%     traj.truthState(2,:)',...
%     traj.truthState(3,:)');
% h_nav = plot3(traj.navState(1,:)',...
%     traj.navState(2,:)',...
%     traj.navState(3,:)');
% xlabel('X (m)')
% ylabel('Y (m)')
% zlabel('Z (m)')
% legend([h_true(1), h_nav(1)], 'Truth Trajectory', 'Navigation Estimate')
% title('Trajectory Propagation')
% grid on;
% axis equal;
end